name: Install
description: Install yarn application and dependencies

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
    - run: corepack enable
      shell: sh
    - uses: actions/setup-node@v4
      with:
        cache: yarn
    - run: yarn install --immutable
      shell: sh
