name: Install
description: Install yarn application and dependencies
inputs:
  node-version:
    default: "22.14"
    required: true
    description: Version of Node.js to use

runs:
  using: composite
  steps:
    - run: corepack enable
      shell: sh
    - uses: actions/setup-node@v4
      with:
        cache: yarn
        node-version: ${{ inputs.node-version }}
    - run: yarn install --immutable
      shell: sh

